name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: rustup update nightly && rustup default nightly && rustup +nightly component add miri
    - name: Build
      run: cargo build --verbose && cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Miri
      run: cargo miri test --verbose
